In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./jobs.csv')
df.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,{'title': '4 Bed House with En Suite at Runda'},{'title': '4 Bed Townhouse with En Suite in La...,{'title': '5 Bed House with En Suite in Nyari'},{'title': '5 Bed House with En Suite in Muthai...,{'title': '5 Bed Townhouse with En Suite in La...,{'title': '5 Bed House with En Suite at Mioton...,{'title': '4 Bed House with En Suite in Muthai...,{'title': '5 Bed House with En Suite at Rosslyn'},{'title': '7 Bed Villa with En Suite in Diani'},{'title': '3 Bed House with En Suite at Runda ...,{'title': '4 Bed House with En Suite in Ruiru'},{'title': '5 Bed Townhouse with En Suite in Ri...,{'title': '5 Bed Villa with En Suite in Karen'},{'title': '3 Bed House with En Suite at Rosslyn'},{'title': '4 Bed House with En Suite in Kilele...,{'title': '4 Bed House with En Suite at Mutero...,{'title': '3 Bed House with En Suite at Runda'}
2,2,{'title': '3 Bed House with En Suite in Rosslyn'},{'title': '1 Bed House with Garden at Loresho'},{'title': '4 Bed House with En Suite in Karen'},{'title': '4 Bed Townhouse with Swimming Pool ...,{'title': '1 Bed House with En Suite in Ridgew...,{'title': '4 Bed House with En Suite at Karen'},{'title': '4 Bed House with Garden at Loresho'},{'title': '4 Bed House with En Suite at Kiambu...,{'title': '4 Bed Townhouse with En Suite in La...,{'title': '4 Bed House with En Suite at Runda ...,{'title': '5 Bed House with En Suite at Mutero'},{'title': '4 Bed House with En Suite in Nyali ...,{'title': '2 Bed House with En Suite at Kilele...,{'title': '4 Bed Townhouse with En Suite in Lo...,{'title': '4 Bed Villa with En Suite in Karen'},NaN,NaN
3,3,{'title': '4 Bed Villa with En Suite in Laving...,{'title': '4 Bed House with En Suite in Nyari'},{'title': '4 Bed House with En Suite at Kiambu...,{'title': '4 Bed House with En Suite in Loresho'},{'title': '4 Bed House with En Suite at Runda ...,{'title': '4 Bed House with En Suite in Rivers...,{'title': '4 Bed House with En Suite at Bongan...,{'title': '4 Bed House with En Suite at Miotoni'},{'title': '4 Bed House with En Suite in Runda'},{'title': '4 Bed Townhouse with En Suite in Ki...,{'title': '5 Bed House with Garden at Karen Ro...,{'title': '3 Bed House with Garden at Miotoni ...,{'title': '4 Bed House with En Suite at Runda'},{'title': '2 Bed House with En Suite at Ndege ...,{'title': '2 Bed House with En Suite at Runda'},NaN,NaN
4,4,{'title': '4 Bed House with En Suite at Eden V...,{'title': '1 Bed House with Garden at Hardy To...,{'title': '4 Bed House with En Suite at Runda'},{'title': '4 Bed Townhouse with En Suite in Jo...,{'title': '4 Bed Villa with En Suite in Kitisu...,{'title': '4 Bed House with En Suite at Runda'},{'title': '4 Bed Townhouse with En Suite at Ma...,{'title': '4 Bed Villa with En Suite in Kiambu...,{'title': '4 Bed Villa with En Suite at Kikamb...,{'title': '4 Bed Townhouse with Garden in Thika'},{'title': '4 Bed Villa with En Suite in Rosslyn'},{'title': '4 Bed House with En Suite at Kiambu...,{'title': '4 Bed House with En Suite at Kerara...,{'title': '5 Bed House with En Suite at Muthai...,{'title': '4 Bed House with En Suite in Karen'},NaN,NaN
5,5,{'title': '4 Bed Townhouse with En Suite in Ru...,{'title': '3 Bed House with En Suite at Westla...,{'title': '4 Bed House with En Suite at Runda'},{'title': '4 Bed Townhouse with Swimming Pool ...,{'title': 'House in Karen Hardy'},{'title': '6 Bed House with En Suite at Mimosa'},{'title': '4 Bed Townhouse with En Suite in La...,{'title': '3 Bed House with En Suite in Rosslyn'},{'title': '4 Bed House with En Suite in Karen'},{'title': '2 Bed House with En Suite at Karen'},{'title': '4 Bed House with En Suite at Bomas'},{'title': '5 Bed House with En Suite at Karen'},{'title': '1 Bed House with En Suite in Runda'},{'title': '4 Bed House with En Suite at Kiambu...,{'title': '4 Bed Villa with En Suite in Athi R...,NaN,NaN
6,6,{'title': '4 Bed House with Garden at Runda'},{'title': '4 Bed House with En Suite at Runda'},{'title': '3 Bed House with En Suite in Spring...,{'title': '5 Bed House with En Suite at Karen'},{'title': '5 Bed House with En Suite in Runda'},{'title': '4 Bed Townhouse with En Suite in Ny...,{'title': '7 Bed House with En Suite at Karen'},{'title': '5 Bed Townhouse in Lavington'},{'title': '4 Bed Townhouse with En Suite at Pe...,{'title': '4 Bed Townhouse with En Suite in La...,{'title': '4 Bed House with En Suite in Karura'},{'title': '5 Bed House with En Suite at Kaumon...,{'title': '5 Bed House with Garden at Kitisuru'},{'title': '4 Bed House with En Suite in Karen'},{'title': '5 Bed House with En Suite at Runda ...,NaN,NaN
7,7,{'title': '4 Bed House with En Suite at Runda'},{'title': '3 Bed House with En Suite at Kuro R...,{'title': '5 Bed House with En Suite in Kitisu...,{'title': '3 Bed Townhouse with En Suite at Gr...,{'title': '4 Bed Townhouse with En Suite in Ki...,{'title': '5 Bed Townhouse in Kileleshwa'},{'title': '4 Bed House with En Suite at Lower ...,{'title': '5 Bed Townhouse with En Suite in La...,{'title': '5 Bed Townhouse with En Suite at Lo...,{'title': '5 Bed Townhouse with En Suite in Ki...,{'title': '3 Bed Townhouse with En Suite in Gi...,{'title': '3 Bed House with En Suite at Karen'},{'title': '5 Bed House with En Suite at Karen'},{'title': '5 Bed Townhouse with En Suite at Ea...,{'title': '4 Bed House with En Suite at Karen'},NaN,NaN
8,8,{'title': '5 Bed House with En Suite in Karen'},{'title': '5 Bed Villa with En Suite in Laving...,{'title': '3 Bed House with En Suite at Matund...,{'title': '3 Bed House with En Suite in Thigiri'},{'title': '5 Bed House with En Suite in Runda'},{'title': '4 Bed House with En Suite at Lower ...,{'title': '4 Bed Townhouse with En Suite at La...,{'title': '4 Bed House with En Suite at Lower ...,{'title': '5 Bed House with Garden in Nyari'},{'title': '4 Bed House with En Suite in Karura'},{'title': '5 Bed House with En Suite at Karen ...,{'title': '5 Bed Townhouse with En Suite at Sp...,{'title': '5 Bed Townhouse with En Suite at Ma...,{'title': '4 Bed House with En Suite at Runda'},{'title': '3 Bed House with En Suite in Ridgew...,NaN,NaN
9,9,{'title': '4 Bed House with En Suite in Muthai...,{'title': '7 Bed House with En Suite at Hillcr...,{'title': '4 Bed House with En Suite at Runda'},{'title': 'Townhouse in Lavington'},{'title': '1 Bed House in Runda'},{'title': '5 Bed House with Swimming Pool at M...,{'title': '4 Bed Townhouse with En Suite in Ru...,{'title': '5 Bed House with En Suite at Chalbi...,{'title': '5 Bed House in Nyari'},{'title': '2 Bed House with En Suite at Karen'},{'title': '5 Bed Townhouse with En Suite in La...,{'title': '4 Bed Townhouse with En Suite in Ru...,{'title': '5 Bed House with En Suite at Flame ...,{'title': '4 Bed House with En Suite in Lower ...,{'title': '1 Bed House with En Suite in Laving...,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   0           9 non-null      object
 2   1           9 non-null      object
 3   2           9 non-null      object
 4   3           9 non-null      object
 5   4           9 non-null      object
 6   5           9 non-null      object
 7   6           9 non-null      object
 8   7           9 non-null      object
 9   8           9 non-null      object
 10  9           9 non-null      object
 11  10          9 non-null      object
 12  11          9 non-null      object
 13  12          9 non-null      object
 14  13          9 non-null      object
 15  14          9 non-null      object
 16  15          1 non-null      object
 17  16          1 non-null      object
dtypes: int64(1), object(17)
memory usage: 1.5+ KB